### ISSUE TITLE
Not working in 2024.9.0

### ISSUE THREAD

**Issue by k-korn** [artem-sedykh/mini-climate-card#156]
On the latest HA version the card is not displaying, with the following error in the browser console:

```
Uncaught (in promise) TypeError: (intermediate value)(intermediate value)(intermediate value).importNode is not a function
    at ed.u (mini-climate-card-bundle.js?hacstag=268163975270:1:21785)
    at fd.g (mini-climate-card-bundle.js?hacstag=268163975270:1:23553)
    at fd._$AI (mini-climate-card-bundle.js?hacstag=268163975270:1:23086)
    at md (mini-climate-card-bundle.js?hacstag=268163975270:1:26659)
    at Xj.update (mini-climate-card-bundle.js?hacstag=268163975270:1:27046)
    at Xj.performUpdate (mini-climate-card-bundle.js?hacstag=268163975270:1:17939)
    at Xj.scheduleUpdate (mini-climate-card-bundle.js?hacstag=268163975270:1:17369)
    at mini-climate-card-bundle.js?hacstag=268163975270:1:17274
    at Generator.next (<anonymous>)
    at t (mini-climate-card-bundle.js?hacstag=268163975270:1:1205)
```

**Comment by regevbr** [comment]
works for me, are you sure you are on the latest version? 
If so, please refer to this comment that explains you need to disable a chomre flag to solve that error:
https://github.com/artem-sedykh/mini-climate-card/issues/137#issuecomment-1869472243

**Comment by k-korn** [comment]
Thanks, that's exactly it.
